version: '3'
services:
  php2:
    build: './php'
    image: php:7.1-fpm
    container_name: php2
    volumes:
      - .:/var/www/sites
      - ./php/php.ini:/usr/local/etc/php/php.ini
    entrypoint:
      - php-fpm
    
  postgresql2:
    image: postgres:latest
    container_name: postgresql2
    build: './postgres'
    expose:
      - 5432
    environment:
      POSTGRES_USER: 'cedric'
      POSTGRES_PASSWORD: 'frost-marker'
      POSTGRES_DB: 'postgres'
      # PGDATA: /tmp5
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/
      - ./postgres/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  nginx2:
    image: nginx:alpine
    container_name: nginx2
    volumes_from:
      - php
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    ports:
      - 8080:80

