version: '2'
services:
  php2:
    build: './php'
    image: php:7.1-fpm
    container_name: php2
    volumes:
      - ./sites:/var/www/sites
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/php.ini:/usr/local/etc/php/php.ini
    entrypoint:
      - php-fpm
    
  postgresql2:
    image: postgres:latest
    container_name: postgresql2
    build: './postgres'
    expose:
      - 5432
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'frost-marker'
      POSTGRES_DB: 'postgres'
    volumes:
      # - ./data/postgres/:/var/lib/postgresql/data/
      - ./postgres/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  nginx2:
    image: nginx:alpine
    container_name: nginx2
    depends_on:
      - php2
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php2
    ports:
      - 8080:80

